In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("preprocessed_urls_hanam_restaurant_real_url_category.csv")
df

     Unnamed: 0                        name  category
0             0                         두숫놈      포장마차
1             1            해장요리전문 임사부국밥 미사점        국밥
2             2         바이더크릭(by the creek)     맥주,호프
3             3  카멜레온 다이닝(CHAMELEON DINING)      요리주점
4             4                  낙원할머니뼛칼 본점        한식
..          ...                         ...       ...
994         994                    장다리 한우마당     소고기구이
995         995                    이정수치킨전문점    치킨,닭강정
996         996                    소문난손칼국수집    칼국수,만두
997         997                     피맥 플레이스        피자
998         998                        구림장어  장어,먹장어요리

[999 rows x 3 columns]

In [6]:
for i, cat in enumerate(df["category"].unique()):
    print(i, '\t', cat, '\t', cat)

0 	 포장마차 	 포장마차
1 	 국밥 	 국밥
2 	 맥주,호프 	 맥주,호프
3 	 요리주점 	 요리주점
4 	 한식 	 한식
5 	 중식당 	 중식당
6 	 베트남음식 	 베트남음식
7 	 다이어트,샐러드 	 다이어트,샐러드
8 	 육류,고기요리 	 육류,고기요리
9 	 해물,생선요리 	 해물,생선요리
10 	 도시락,컵밥 	 도시락,컵밥
11 	 초밥,롤 	 초밥,롤
12 	 족발,보쌈 	 족발,보쌈
13 	 곱창,막창,양 	 곱창,막창,양
14 	 치킨,닭강정 	 치킨,닭강정
15 	 소고기구이 	 소고기구이
16 	 아귀찜,해물찜 	 아귀찜,해물찜
17 	 카페 	 카페
18 	 닭갈비 	 닭갈비
19 	 케이크전문 	 케이크전문
20 	 카페,디저트 	 카페,디저트
21 	 두부요리 	 두부요리
22 	 양식 	 양식
23 	 피자 	 피자
24 	 백반,가정식 	 백반,가정식
25 	 만두 	 만두
26 	 주꾸미요리 	 주꾸미요리
27 	 베이커리 	 베이커리
28 	 오징어요리 	 오징어요리
29 	 막국수 	 막국수
30 	 죽 	 죽
31 	 돼지고기구이 	 돼지고기구이
32 	 순대,순댓국 	 순대,순댓국
33 	 햄버거 	 햄버거
34 	 곰탕,설렁탕 	 곰탕,설렁탕
35 	 이자카야 	 이자카야
36 	 식료품 	 식료품
37 	 뷔페 	 뷔페
38 	 한식뷔페 	 한식뷔페
39 	 찌개,전골 	 찌개,전골
40 	 덮밥 	 덮밥
41 	 분식 	 분식
42 	 마라탕 	 마라탕
43 	 샤브샤브 	 샤브샤브
44 	 돈가스 	 돈가스
45 	 딤섬,중식만두 	 딤섬,중식만두
46 	 국수 	 국수
47 	 떡볶이 	 떡볶이
48 	 감자탕 	 감자탕
49 	 브런치카페 	 브런치카페
50 	 닭요리 	 닭요리
51 	 일식당 	 일식당
52 	 닭발 	 닭발
53 	 추어탕 	 추어탕
54 	 칼국수,만두 	 칼국수,만두
55 	 오뎅,꼬치 	 오뎅,꼬치
56 	 우동,소바 	 우동,소바
57 	 생선회 	 생선회
58 	 고기뷔페 	 고기뷔페
59 	 양어,양식업 	 양어,양식업
60 	 샌드위치 	 샌드위치
61 	 해장국 	 해장국
62 	 오리요리 	 오리요리
63 	 미용실 	 미용실
64 	 종합분식 	 종합분식
65 	 자동차스티커 	 자동차스티커
66 	 장어,먹장어요리 	 장어,먹장어요리
67 	 전,빈대떡 	 전,빈대떡
68 	 라면 	 라면
69 	 토스트 	 토스트
70 	 양갈비 	 양갈비
71 	 호떡 	 호떡
72 	 조개요리 	 조개요리
73 	 이탈리아음식 	 이탈리아음식
74 	 카레 	 카레
75 	 주류 	 주류
76 	 꽃집,꽃배달 	 꽃집,꽃배달
77 	 프랑스음식 	 프랑스음식
78 	 바(BAR) 	 바(BAR)
79 	 스파게티,파스타전문 	 스파게티,파스타전문
80 	 한방카페 	 한방카페
81 	 브런치 	 브런치
82 	 반찬가게 	 반찬가게
83 	 애견카페 	 애견카페
84 	 빙수 	 빙수
85 	 이벤트,파티 	 이벤트,파티
86 	 아시아음식 	 아시아음식
87 	 게요리 	 게요리
88 	 스포츠,오락 	 스포츠,오락
89 	 키즈카페,실내놀이터 	 키즈카페,실내놀이터
90 	 테이크아웃커피 	 테이크아웃커피
91 	 정육점 	 정육점
92 	 태국음식 	 태국음식
93 	 와인 	 와인
94 	 과일,주스전문점 	 과일,주스전문점
95 	 정육식당 	 정육식당
96 	 일본식라면 	 일본식라면
97 	 주류제조 	 주류제조
98 	 캠핑용품 	 캠핑용품
99 	 쌈밥 	 쌈밥
100 	 감성낙곱새 	 감성낙곱새
101 	 라이브카페 	 라이브카페
102 	 백숙,삼계탕 	 백숙,삼계탕
103 	 당구장 	 당구장
104 	 매운탕,해물탕 	 매운탕,해물탕
105 	 아부찌부대찌개 	 아부찌부대찌개
106 	 밀키트 	 밀키트
107 	 기타 	 기타
108 	 김밥 	 김밥
109 	 찜닭 	 찜닭
110 	 냉면 	 냉면
111 	 갈비탕 	 갈비탕
112 	 전통,민속주점 	 전통,민속주점
113 	 독일음식 	 독일음식
114 	 화덕고깃간 	 화덕고깃간
115 	 식품 	 식품
116 	 물류,유통 	 물류,유통
117 	 낙지요리 	 낙지요리
118 	 멕시코,남미음식 	 멕시코,남미음식
119 	 한정식 	 한정식
120 	 스테이크,립 	 스테이크,립
121 	 출장요리 	 출장요리
122 	 사철,영양탕 	 사철,영양탕
123 	 양꼬치 	 양꼬치
124 	 놀이기구 	 놀이기구
125 	 복어요리 	 복어요리

In [7]:
df1 = pd.read_csv("preprocessed_category_v1.csv")

In [8]:
df1["category"].value_counts()

category
고기      13
한식당     11
해물      10
카페       7
분식       6
        ..
해장국      1
미용실      1
전        1
카레       1
복어요리     1
Name: count, Length: 68, dtype: int64

In [9]:
df2 = pd.read_csv("preprocessed_category_v2.csv")

In [10]:
df_pre = pd.read_csv("preprocessed_urls_hanam_restaurant_real_url_category.csv")

In [11]:
df_pre

     Unnamed: 0                        name  category
0             0                         두숫놈      포장마차
1             1            해장요리전문 임사부국밥 미사점        국밥
2             2         바이더크릭(by the creek)     맥주,호프
3             3  카멜레온 다이닝(CHAMELEON DINING)      요리주점
4             4                  낙원할머니뼛칼 본점        한식
..          ...                         ...       ...
994         994                    장다리 한우마당     소고기구이
995         995                    이정수치킨전문점    치킨,닭강정
996         996                    소문난손칼국수집    칼국수,만두
997         997                     피맥 플레이스        피자
998         998                        구림장어  장어,먹장어요리

[999 rows x 3 columns]

In [12]:
cate_dict = {}

for i in range(len(df2)):
    cate_dict[df2.iloc[i]["name"]] = df2.iloc[i]["category"]

for key, val in cate_dict.items():
    print(key, val)

포장마차 식당
국밥 한식당
맥주 호프 호프
요리주점 식당
한식 한식당
중식당 중국집
베트남음식 아시안 음식
다이어트 샐러드 야채
육류 고기요리 고기
해물 생선요리 해물
도시락 컵밥 식당 아님
초밥 롤 일식집
족발 보쌈 고기
곱창 막창 양 고기
치킨 닭강정 치킨
소고기구이 고기
아귀찜 해물찜 해물
카페 카페
닭갈비 고기
케이크전문 베이커리
카페 디저트 카페
두부요리 한식당
양식 양식
피자 피자
백반 가정식 한식당
만두 분식
주꾸미요리 해물
베이커리 베이커리
오징어요리 해물
막국수 한식당
죽 한식당
돼지고기구이 고기
순대 순댓국 식당
햄버거 햄버거
곰탕 설렁탕 한식당
이자카야 일식집
식료품 식당 아님
뷔페 뷔페
한식뷔페 한식당
찌개 전골 한식당
덮밥 식당
분식 분식
마라탕 중국집
샤브샤브 샤브샤브
돈가스 돈가스
딤섬 중식만두 중국집
국수 분식
떡볶이 분식
감자탕 식당
브런치카페 카페
닭요리 고기
일식당 일식당
닭발 고기
추어탕 식당
칼국수 만두 분식
오뎅 꼬치 일식당
우동 소바 일식당
생선회 일식당
고기뷔페 고기
양어 양식업 해물
샌드위치 간식
해장국 해장국
오리요리 고기
미용실 식당 아님
종합분식 분식
자동차스티커 식당 아님
장어 먹장어요리 해물
전 빈대떡 식당
라면 분식
토스트 간식
양갈비 고기
호떡 간식
조개요리 해물
이탈리아음식 양식
카레 식당
주류 주류
꽃집 꽃배달 식당 아님
프랑스음식 양식
바(BAR) 주류
스파게티 파스타전문 양식
한방카페 카페
브런치 까페
반찬가게 식당
애견카페 카페
빙수 디저트
이벤트 파티 식당 아님
아시아음식 아시안 음식
게요리 해물
스포츠 오락 식당 아님
키즈카페 실내놀이터 카페
테이크아웃커피 카페
정육점 고기
태국음식 아시안 음식
와인 주류
과일 주스전문점 카페
정육식당 고기
일본식라면 일식당
주류제조 식당 아님
캠핑용품 식당 아님
쌈밥 한식당
감성낙곱새 해물
라이브카페 카페
백숙 삼계탕 한식당
당구장 식당 아님
매운탕 해물탕 해물
아부찌부대찌개 한식당
밀키트 식당 아님
기타 식당 아님
김밥 분식
찜닭 한식당
냉면 한식당
갈비탕 한식당
전통 민속주점 주류
독일음식 양식
화덕고깃간 고기
식품 식당
물류 유통 식당 아님
낙지요리 해물
멕시코 남미음식 식당
한정식 한식당
스테이크 립 양식
출장요리 식당
사철 영양탕 한식당
양꼬치 중국집
놀이기구 식당 아님
복어요리 해물

In [15]:
df_pre['category2'] = df_pre["category"].copy().apply(lambda x: x.replace(x, x.replace(',', ' ').replace('"', '')))
df_pre

     Unnamed: 0                        name  category category2
0             0                         두숫놈      포장마차      포장마차
1             1            해장요리전문 임사부국밥 미사점        국밥        국밥
2             2         바이더크릭(by the creek)     맥주,호프     맥주 호프
3             3  카멜레온 다이닝(CHAMELEON DINING)      요리주점      요리주점
4             4                  낙원할머니뼛칼 본점        한식        한식
..          ...                         ...       ...       ...
994         994                    장다리 한우마당     소고기구이     소고기구이
995         995                    이정수치킨전문점    치킨,닭강정    치킨 닭강정
996         996                    소문난손칼국수집    칼국수,만두    칼국수 만두
997         997                     피맥 플레이스        피자        피자
998         998                        구림장어  장어,먹장어요리  장어 먹장어요리

[999 rows x 4 columns]

In [21]:
df_pre["category3"] = df_pre['category2'].apply(lambda x : x.replace(x, cate_dict[x]))
# df_pre

df_post = df_pre[["name", "category3"]]
df_post.to_csv("category.csv")

In [22]:
df_post

                           name category3
0                           두숫놈        식당
1              해장요리전문 임사부국밥 미사점       한식당
2           바이더크릭(by the creek)        호프
3    카멜레온 다이닝(CHAMELEON DINING)        식당
4                    낙원할머니뼛칼 본점       한식당
..                          ...       ...
994                    장다리 한우마당        고기
995                    이정수치킨전문점        치킨
996                    소문난손칼국수집        분식
997                     피맥 플레이스        피자
998                        구림장어        해물

[999 rows x 2 columns]